USE ALICE_DEVELOPMENT;
GO
-- Truncate the log by changing the database recovery model to SIMPLE.
ALTER DATABASE ALICE_DEVELOPMENT
SET RECOVERY SIMPLE;
GO
-- Shrink the truncated log file to 1 MB.
DBCC SHRINKFILE (ALICE_DEVELOPMENT, 1);
GO
-- Reset the database recovery model.
ALTER DATABASE ALICE_DEVELOPMENT
SET RECOVERY FULL;
GO

DBCC SHRINKDATABASE (ALICE_DEVELOPMENT, 10);
GO